# Generated by Django 4.0.3 on 2024-03-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=4)),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
